languageCode = "en-us"
title = "Rfun"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-dopetrope"

[params.portfolio]
    title = "Our Workshops"
    foldername = "workshops"
    findoutmoretext = "Find out more"

[params.blog]
    title = "Rfun Blog"
    viewalltext = "View All"
    foldername = "blog"

#[params.settings]
#    googleanalytics = "UA-113904582-1"
#    disqus = "hugo-dopetrope"
    
    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
