---
title: Visualization in R using ggplot2
author: John Little
date: '2018-08-10'
slug: visualization-in-r-using-ggplot2
categories: ["ggplot2","Visualization", "Workshops"]
tags: ["R Markdown", "plot", "regression"]
---

Angela Zoss ([DVS Staff page](https://library.duke.edu/data/about/staff)) presents a **visualization** workshop hosted by the [Data and Visualization Services Department](https://library.duke.edu/data/).

The workshops, officially entitled *Visualization in R using ggplot2*, is a two-hour, hands-on learning session designed to introduce the **ggplot2** package, a programming library within the R programming language.  The ggplot2 library for R creates clear and well-designed visualizations  that plays well with other tidyverse packages. 

Data science skills are increasingly important for research and industry projects.  With complex data science projects, however, come complex needs for understanding and communicating analysis processes and results.  Ultimately, an analyst's data science toolbox is incomplete without visualization skills.  Incorporating effective visualizations directly into the analysis tool you are using can facilitate quick data exploration, streamline your research process, and improve the reproducibility of your research.

**Learning resources** and **workshop materials** are available and shareable.  Use the links below to learn at your own pace and at the comfort of your own workspace.  

- [Streaming Video](https://library.capture.duke.edu/Panopto/Pages/Viewer.aspx?id=d7516f8a-1d1c-42d9-ad66-6534ffaec690)
- [GitHub Code](https://github.com/amzoss/ggplot2-F17)
- [DVS Description / Resources](http://duke.libcal.com/event/3442555)
